// Seed data for clubs across Canadian provinces
import { db } from "./db-connection";
import { clubs } from "../schema/clubs";

export const clubsData = [
  // British Columbia (5 clubs)
  {
    name: "Royal Vancouver Curling Club",
    slug: "royal-vancouver-cc",
    province: "BC",
    city: "Vancouver",
    address: "1630 West King Edward Avenue",
    postalCode: "V6J 2S3",
    phone: "604-733-7220",
    email: "info@royalvancouver.ca",
    website: "https://www.royalvancouver.ca",
    description: "Founded in 1906, the Royal Vancouver Curling Club is one of the oldest and most prestigious curling clubs in Western Canada.",
    numberOfSheets: 8,
    hasProfessionalShop: true,
    hasRestaurant: true,
    hasLounge: true,
    membershipType: "private",
    isActive: true,
  },
  {
    name: "Kelowna Curling Club",
    slug: "kelowna-cc",
    province: "BC",
    city: "Kelowna",
    address: "1188 Recreation Avenue",
    postalCode: "V1Y 7Z3",
    phone: "250-762-2824",
    email: "manager@kelownacurlingclub.com",
    website: "https://www.kelownacurlingclub.com",
    description: "Premier curling facility in the Okanagan Valley with modern amenities.",
    numberOfSheets: 6,
    hasProfessionalShop: true,
    hasRestaurant: false,
    hasLounge: true,
    membershipType: "public",
    isActive: true,
  },
  {
    name: "Victoria Curling Club",
    slug: "victoria-cc",
    province: "BC",
    city: "Victoria",
    address: "1952 Quadra Street",
    postalCode: "V8T 4B8",
    phone: "250-385-4434",
    email: "info@victoriacurlingclub.ca",
    website: "https://www.victoriacurlingclub.ca",
    description: "Vancouver Island's premier curling facility since 1950.",
    numberOfSheets: 5,
    hasProfessionalShop: false,
    hasRestaurant: true,
    hasLounge: true,
    membershipType: "public",
    isActive: true,
  },
  {
    name: "Prince George Golf and Curling Club",
    slug: "prince-george-gcc",
    province: "BC",
    city: "Prince George",
    address: "2929 Country Club Drive",
    postalCode: "V2N 5B7",
    phone: "250-564-7332",
    email: "info@pggcc.ca",
    website: "https://www.pggcc.ca",
    description: "Year-round facility with golf and curling in Northern BC.",
    numberOfSheets: 4,
    hasProfessionalShop: true,
    hasRestaurant: true,
    hasLounge: true,
    membershipType: "private",
    isActive: true,
  },
  {
    name: "Kamloops Curling Club",
    slug: "kamloops-cc",
    province: "BC",
    city: "Kamloops",
    address: "610 Chilcotin Road",
    postalCode: "V2H 1B1",
    phone: "250-376-3343",
    email: "manager@kamloopscurling.com",
    website: "https://www.kamloopscurling.com",
    description: "Community-focused curling club in the heart of BC's interior.",
    numberOfSheets: 6,
    hasProfessionalShop: false,
    hasRestaurant: false,
    hasLounge: true,
    membershipType: "public",
    isActive: true,
  },

  // Alberta (6 clubs)
  {
    name: "Calgary Winter Club",
    slug: "calgary-winter-club",
    province: "AB",
    city: "Calgary",
    address: "615 10th Avenue SW",
    postalCode: "T2R 0B4",
    phone: "403-266-1241",
    email: "info@calgarywinterclub.ca",
    website: "https://www.calgarywinterclub.ca",
    description: "Historic private club established in 1908, home to numerous provincial and national champions.",
    numberOfSheets: 10,
    hasProfessionalShop: true,
    hasRestaurant: true,
    hasLounge: true,
    membershipType: "private",
    isActive: true,
  },
  {
    name: "Saville Community Sports Centre",
    slug: "saville-sports-centre",
    province: "AB",
    city: "Edmonton",
    address: "11610 65th Street NW",
    postalCode: "T5W 4K1",
    phone: "780-496-7275",
    email: "curling@savillesports.ca",
    website: "https://www.savillesports.ca",
    description: "Edmonton's premier curling facility with 8 sheets and modern amenities.",
    numberOfSheets: 8,
    hasProfessionalShop: true,
    hasRestaurant: true,
    hasLounge: true,
    membershipType: "public",
    isActive: true,
  },
  {
    name: "Lethbridge Curling Club",
    slug: "lethbridge-cc",
    province: "AB",
    city: "Lethbridge",
    address: "2510 Scenic Drive South",
    postalCode: "T1K 7H7",
    phone: "403-327-1923",
    email: "manager@lethbridgecurling.ca",
    website: "https://www.lethbridgecurling.ca",
    description: "Southern Alberta's premier curling facility hosting provincial championships.",
    numberOfSheets: 6,
    hasProfessionalShop: true,
    hasRestaurant: false,
    hasLounge: true,
    membershipType: "public",
    isActive: true,
  },
  {
    name: "Red Deer Curling Centre",
    slug: "red-deer-cc",
    province: "AB",
    city: "Red Deer",
    address: "6841 20th Street",
    postalCode: "T4P 3R9",
    phone: "403-347-2444",
    email: "info@rdcurling.ca",
    website: "https://www.rdcurling.ca",
    description: "Central Alberta's largest curling facility with excellent ice conditions.",
    numberOfSheets: 8,
    hasProfessionalShop: true,
    hasRestaurant: true,
    hasLounge: true,
    membershipType: "public",
    isActive: true,
  },
  {
    name: "Grande Prairie Curling Centre",
    slug: "grande-prairie-cc",
    province: "AB",
    city: "Grande Prairie",
    address: "10401 98th Street",
    postalCode: "T8V 2E7",
    phone: "780-532-0115",
    email: "manager@gpcurling.ca",
    website: "https://www.gpcurling.ca",
    description: "Northern Alberta's premier curling facility serving the Peace Region.",
    numberOfSheets: 6,
    hasProfessionalShop: false,
    hasRestaurant: false,
    hasLounge: true,
    membershipType: "public",
    isActive: true,
  },
  {
    name: "Jasper Curling Club",
    slug: "jasper-cc",
    province: "AB",
    city: "Jasper",
    address: "307 Bonhomme Street",
    postalCode: "T0E 1E0",
    phone: "780-852-3613",
    email: "info@jaspercurling.ca",
    website: "https://www.jaspercurling.ca",
    description: "Scenic mountain curling club in Jasper National Park.",
    numberOfSheets: 4,
    hasProfessionalShop: false,
    hasRestaurant: false,
    hasLounge: true,
    membershipType: "public",
    isActive: true,
  },

  // Saskatchewan (5 clubs)
  {
    name: "Regina Curling Centre",
    slug: "regina-cc",
    province: "SK",
    city: "Regina",
    address: "2250 13th Avenue",
    postalCode: "S4P 0V7",
    phone: "306-781-1809",
    email: "info@reginacurling.ca",
    website: "https://www.reginacurling.ca",
    description: "Saskatchewan's largest curling facility, home of numerous national events.",
    numberOfSheets: 12,
    hasProfessionalShop: true,
    hasRestaurant: true,
    hasLounge: true,
    membershipType: "public",
    isActive: true,
  },
  {
    name: "Granite Curling Club",
    slug: "granite-saskatoon",
    province: "SK",
    city: "Saskatoon",
    address: "420 Crescent Boulevard",
    postalCode: "S7N 2X1",
    phone: "306-652-1563",
    email: "manager@granitecurling.ca",
    website: "https://www.granitecurling.ca",
    description: "Historic Saskatoon club with a proud tradition of competitive curling.",
    numberOfSheets: 8,
    hasProfessionalShop: true,
    hasRestaurant: true,
    hasLounge: true,
    membershipType: "private",
    isActive: true,
  },
  {
    name: "Moose Jaw Curling Centre",
    slug: "moose-jaw-cc",
    province: "SK",
    city: "Moose Jaw",
    address: "1234 Caribou Street West",
    postalCode: "S6H 2M7",
    phone: "306-692-5464",
    email: "mjcurling@sasktel.net",
    website: "https://www.moosejawcurling.ca",
    description: "Community curling club with strong junior and senior programs.",
    numberOfSheets: 6,
    hasProfessionalShop: false,
    hasRestaurant: false,
    hasLounge: true,
    membershipType: "public",
    isActive: true,
  },
  {
    name: "Yorkton Curling Centre",
    slug: "yorkton-cc",
    province: "SK",
    city: "Yorkton",
    address: "375 Dracup Avenue",
    postalCode: "S3N 3K6",
    phone: "306-783-9447",
    email: "info@yorktoncurling.ca",
    website: "https://www.yorktoncurling.ca",
    description: "Modern facility serving East Central Saskatchewan.",
    numberOfSheets: 5,
    hasProfessionalShop: false,
    hasRestaurant: false,
    hasLounge: true,
    membershipType: "public",
    isActive: true,
  },
  {
    name: "Prince Albert Curling Club",
    slug: "prince-albert-cc",
    province: "SK",
    city: "Prince Albert",
    address: "1010 Marquis Road",
    postalCode: "S6V 7N6",
    phone: "306-763-6565",
    email: "info@princealbertcurling.ca",
    website: "https://www.princealbertcurling.ca",
    description: "Northern Saskatchewan's premier curling facility.",
    numberOfSheets: 6,
    hasProfessionalShop: false,
    hasRestaurant: true,
    hasLounge: true,
    membershipType: "public",
    isActive: true,
  },

  // Manitoba (4 clubs)
  {
    name: "Fort Rouge Curling Club",
    slug: "fort-rouge-cc",
    province: "MB",
    city: "Winnipeg",
    address: "625 Osborne Street",
    postalCode: "R3L 2B2",
    phone: "204-284-7560",
    email: "info@fortrougecurling.com",
    website: "https://www.fortrougecurling.com",
    description: "Historic Winnipeg club, host of the 2013 Scotties Tournament of Hearts.",
    numberOfSheets: 6,
    hasProfessionalShop: true,
    hasRestaurant: true,
    hasLounge: true,
    membershipType: "private",
    isActive: true,
  },
  {
    name: "Assiniboine Memorial Curling Club",
    slug: "assiniboine-memorial",
    province: "MB",
    city: "Winnipeg",
    address: "827 Wellington Crescent",
    postalCode: "R3M 0C1",
    phone: "204-284-3640",
    email: "manager@amcurling.ca",
    website: "https://www.amcurling.ca",
    description: "Premier private curling club in Winnipeg with a rich competitive history.",
    numberOfSheets: 8,
    hasProfessionalShop: true,
    hasRestaurant: true,
    hasLounge: true,
    membershipType: "private",
    isActive: true,
  },
  {
    name: "Brandon Curling Club",
    slug: "brandon-cc",
    province: "MB",
    city: "Brandon",
    address: "1017 Queens Crescent",
    postalCode: "R7A 1L8",
    phone: "204-727-2662",
    email: "info@brandoncurling.ca",
    website: "https://www.brandoncurling.ca",
    description: "Western Manitoba's premier curling facility with excellent programs.",
    numberOfSheets: 6,
    hasProfessionalShop: false,
    hasRestaurant: true,
    hasLounge: true,
    membershipType: "public",
    isActive: true,
  },
  {
    name: "Portage Curling Club",
    slug: "portage-cc",
    province: "MB",
    city: "Portage la Prairie",
    address: "55 Royal Road North",
    postalCode: "R1N 1T8",
    phone: "204-857-6681",
    email: "manager@portagecurling.ca",
    website: "https://www.portagecurling.ca",
    description: "Community-focused club serving South Central Manitoba.",
    numberOfSheets: 5,
    hasProfessionalShop: false,
    hasRestaurant: false,
    hasLounge: true,
    membershipType: "public",
    isActive: true,
  },

  // Ontario (6 clubs)
  {
    name: "High Park Club",
    slug: "high-park-club",
    province: "ON",
    city: "Toronto",
    address: "100 Indian Road",
    postalCode: "M6R 2V5",
    phone: "416-769-2811",
    email: "info@highparkclub.com",
    website: "https://www.highparkclub.com",
    description: "Toronto's premier private curling and social club since 1928.",
    numberOfSheets: 8,
    hasProfessionalShop: true,
    hasRestaurant: true,
    hasLounge: true,
    membershipType: "private",
    isActive: true,
  },
  {
    name: "Tam Heather Curling Club",
    slug: "tam-heather-cc",
    province: "ON",
    city: "Toronto",
    address: "481 Dunedin Avenue",
    postalCode: "M6C 2G6",
    phone: "416-654-1621",
    email: "manager@tamheather.ca",
    website: "https://www.tamheather.ca",
    description: "Community-focused Toronto curling club with strong league programs.",
    numberOfSheets: 6,
    hasProfessionalShop: false,
    hasRestaurant: false,
    hasLounge: true,
    membershipType: "public",
    isActive: true,
  },
  {
    name: "Ottawa Curling Club",
    slug: "ottawa-cc",
    province: "ON",
    city: "Ottawa",
    address: "1148 Wellington Street West",
    postalCode: "K1Y 2Y9",
    phone: "613-722-5411",
    email: "info@ottawacurlingclub.ca",
    website: "https://www.ottawacurlingclub.ca",
    description: "Historic Ottawa club established in 1851, Canada's oldest curling club.",
    numberOfSheets: 8,
    hasProfessionalShop: true,
    hasRestaurant: true,
    hasLounge: true,
    membershipType: "private",
    isActive: true,
  },
  {
    name: "Royal Canadian Curling Club",
    slug: "rccc-toronto",
    province: "ON",
    city: "Toronto",
    address: "141 Broadview Avenue",
    postalCode: "M4M 2E8",
    phone: "416-465-2022",
    email: "info@royalcanadiancurling.ca",
    website: "https://www.royalcanadiancurling.ca",
    description: "East Toronto's premier curling facility with modern ice technology.",
    numberOfSheets: 6,
    hasProfessionalShop: true,
    hasRestaurant: true,
    hasLounge: true,
    membershipType: "private",
    isActive: true,
  },
  {
    name: "Thornhill Curling Club",
    slug: "thornhill-cc",
    province: "ON",
    city: "Thornhill",
    address: "18 John Street",
    postalCode: "L3T 1X4",
    phone: "905-889-4271",
    email: "manager@thornhillcurling.com",
    website: "https://www.thornhillcurling.com",
    description: "York Region's premier curling facility with active competitive programs.",
    numberOfSheets: 6,
    hasProfessionalShop: false,
    hasRestaurant: false,
    hasLounge: true,
    membershipType: "public",
    isActive: true,
  },
  {
    name: "KW Granite Club",
    slug: "kw-granite",
    province: "ON",
    city: "Waterloo",
    address: "120 Union Street East",
    postalCode: "N2J 1B9",
    phone: "519-743-5622",
    email: "info@kwgranite.com",
    website: "https://www.kwgranite.com",
    description: "Waterloo Region's premier curling facility serving the KW area.",
    numberOfSheets: 8,
    hasProfessionalShop: true,
    hasRestaurant: true,
    hasLounge: true,
    membershipType: "public",
    isActive: true,
  },

  // Quebec (4 clubs)
  {
    name: "Royal Montreal Curling Club",
    slug: "royal-montreal-cc",
    province: "QC",
    city: "Montreal",
    address: "1850 De Maisonneuve Boulevard West",
    postalCode: "H3H 1J9",
    phone: "514-933-2445",
    email: "info@royalmtl.ca",
    website: "https://www.royalmtl.ca",
    description: "North America's first curling club, established in 1807. A historic institution.",
    numberOfSheets: 8,
    hasProfessionalShop: true,
    hasRestaurant: true,
    hasLounge: true,
    membershipType: "private",
    isActive: true,
  },
  {
    name: "Club de Curling Laval-sur-le-Lac",
    slug: "laval-sur-le-lac",
    province: "QC",
    city: "Laval",
    address: "3535 Rue Remembrance",
    postalCode: "H7V 3J9",
    phone: "450-689-8051",
    email: "info@curllaval.com",
    website: "https://www.curllaval.com",
    description: "Premier curling facility in Laval with bilingual programs.",
    numberOfSheets: 6,
    hasProfessionalShop: true,
    hasRestaurant: true,
    hasLounge: true,
    membershipType: "private",
    isActive: true,
  },
  {
    name: "Club de Curling Etchemin",
    slug: "etchemin-cc",
    province: "QC",
    city: "Quebec City",
    address: "3375 Avenue de Rochebelle",
    postalCode: "G1X 4A8",
    phone: "418-658-4235",
    email: "info@curlingetchemin.ca",
    website: "https://www.curlingetchemin.ca",
    description: "Quebec City's premier curling facility with strong competitive programs.",
    numberOfSheets: 6,
    hasProfessionalShop: false,
    hasRestaurant: true,
    hasLounge: true,
    membershipType: "public",
    isActive: true,
  },
  {
    name: "Club de Curling Glenmore",
    slug: "glenmore-cc",
    province: "QC",
    city: "Dollard-des-Ormeaux",
    address: "4300 Saint-Jean Boulevard",
    postalCode: "H9H 2A4",
    phone: "514-626-2311",
    email: "info@glenmorecurling.ca",
    website: "https://www.glenmorecurling.ca",
    description: "West Island Montreal's community curling club.",
    numberOfSheets: 5,
    hasProfessionalShop: false,
    hasRestaurant: false,
    hasLounge: true,
    membershipType: "public",
    isActive: true,
  },
];

export async function seedClubs() {
  console.log("🏒 Seeding clubs...");
  
  try {
    const result = await db.insert(clubs).values(clubsData).returning();
    console.log(`✅ Seeded ${result.length} clubs`);
    return result;
  } catch (error) {
    console.error("❌ Error seeding clubs:", error);
    throw error;
  }
}
