// Seed data for events - competitions, clinics, and social events
import { db } from "./db-connection";
import { events } from "../schema/events";

// Helper to generate dates relative to now
const now = new Date();
const daysAgo = (days: number) => new Date(now.getTime() - days * 24 * 60 * 60 * 1000);
const daysFromNow = (days: number) => new Date(now.getTime() + days * 24 * 60 * 60 * 1000);

export const eventsData = [
  // Major Championships (Past)
  {
    title: "Tim Hortons Brier 2024",
    slug: "brier-2024",
    description: "Canada's Men's Curling Championship featuring the best teams from across the country competing for the Brier Tankard and the right to represent Canada at the World Championship.",
    eventType: "competition",
    category: "championship",
    level: "national",
    startDate: daysAgo(120),
    endDate: daysAgo(112),
    registrationOpenDate: daysAgo(180),
    registrationCloseDate: daysAgo(125),
    city: "Regina",
    province: "SK",
    venueName: "Brandt Centre",
    venueAddress: "1717 Elphinstone Street",
    maxParticipants: 18,
    currentParticipants: 18,
    registrationFee: "0",
    currency: "CAD",
    hasLiveScoring: true,
    hasLiveStream: true,
    streamUrl: "https://www.tsn.ca/curling/brier",
    status: "completed",
    isPublic: true,
    isFeatured: true,
    loyaltyPointsAwarded: 1000,
    prizeMoney: "500000",
    tags: ["championship", "mens", "national", "brier"],
  },
  {
    title: "Scotties Tournament of Hearts 2024",
    slug: "scotties-2024",
    description: "Canada's Women's Curling Championship bringing together provincial champions to compete for the coveted Scotties crown.",
    eventType: "competition",
    category: "championship",
    level: "national",
    startDate: daysAgo(100),
    endDate: daysAgo(92),
    registrationOpenDate: daysAgo(160),
    registrationCloseDate: daysAgo(105),
    city: "Calgary",
    province: "AB",
    venueName: "Stampede Corral",
    venueAddress: "1410 Olympic Way SE",
    maxParticipants: 18,
    currentParticipants: 18,
    registrationFee: "0",
    currency: "CAD",
    hasLiveScoring: true,
    hasLiveStream: true,
    streamUrl: "https://www.tsn.ca/curling/scotties",
    status: "completed",
    isPublic: true,
    isFeatured: true,
    loyaltyPointsAwarded: 1000,
    prizeMoney: "500000",
    tags: ["championship", "womens", "national", "scotties"],
  },

  // Upcoming Major Events
  {
    title: "Canadian Mixed Doubles Championship 2025",
    slug: "mixed-doubles-2025",
    description: "National championship for mixed doubles curling, featuring dynamic two-person teams competing in an exciting format.",
    eventType: "competition",
    category: "championship",
    level: "national",
    startDate: daysFromNow(30),
    endDate: daysFromNow(36),
    registrationOpenDate: daysAgo(30),
    registrationCloseDate: daysFromNow(15),
    city: "Winnipeg",
    province: "MB",
    venueName: "Canada Life Centre",
    venueAddress: "345 Portage Avenue",
    maxParticipants: 32,
    currentParticipants: 28,
    registrationFee: "250",
    currency: "CAD",
    waitlistEnabled: true,
    requiresApproval: true,
    hasLiveScoring: true,
    hasLiveStream: true,
    status: "registration_open",
    isPublic: true,
    isFeatured: true,
    loyaltyPointsAwarded: 500,
    prizeMoney: "150000",
    tags: ["championship", "mixed-doubles", "national"],
  },
  {
    title: "Canadian Junior Curling Championships 2025",
    slug: "juniors-2025",
    description: "National championship for junior curlers (Under 21), showcasing Canada's future stars of the sport.",
    eventType: "competition",
    category: "championship",
    level: "national",
    startDate: daysFromNow(45),
    endDate: daysFromNow(52),
    registrationOpenDate: daysAgo(20),
    registrationCloseDate: daysFromNow(25),
    city: "Ottawa",
    province: "ON",
    venueName: "TD Place Arena",
    venueAddress: "1015 Bank Street",
    maxParticipants: 28,
    currentParticipants: 24,
    registrationFee: "0",
    currency: "CAD",
    requiresApproval: true,
    hasLiveScoring: true,
    hasLiveStream: true,
    status: "registration_open",
    isPublic: true,
    isFeatured: true,
    loyaltyPointsAwarded: 300,
    prizeMoney: "75000",
    tags: ["championship", "juniors", "national", "youth"],
  },

  // Provincial Championships
  {
    title: "BC Men's Curling Championship",
    slug: "bc-mens-2025",
    description: "Provincial championship determining BC's representative at the Tim Hortons Brier.",
    eventType: "competition",
    category: "championship",
    level: "provincial",
    startDate: daysFromNow(20),
    endDate: daysFromNow(24),
    registrationOpenDate: daysAgo(45),
    registrationCloseDate: daysFromNow(10),
    city: "Kelowna",
    province: "BC",
    venueName: "Kelowna Curling Club",
    venueAddress: "1188 Recreation Avenue",
    maxParticipants: 12,
    currentParticipants: 11,
    registrationFee: "500",
    currency: "CAD",
    requiresApproval: true,
    hasLiveScoring: true,
    hasLiveStream: false,
    status: "registration_open",
    isPublic: true,
    isFeatured: false,
    loyaltyPointsAwarded: 200,
    prizeMoney: "10000",
    tags: ["provincial", "mens", "bc"],
  },
  {
    title: "Alberta Women's Curling Championship",
    slug: "ab-womens-2025",
    description: "Top women's teams from Alberta compete for the provincial title and Scotties berth.",
    eventType: "competition",
    category: "championship",
    level: "provincial",
    startDate: daysFromNow(35),
    endDate: daysFromNow(39),
    registrationOpenDate: daysAgo(40),
    registrationCloseDate: daysFromNow(20),
    city: "Red Deer",
    province: "AB",
    venueName: "Red Deer Curling Centre",
    venueAddress: "6841 20th Street",
    maxParticipants: 12,
    currentParticipants: 10,
    registrationFee: "500",
    currency: "CAD",
    requiresApproval: true,
    hasLiveScoring: true,
    hasLiveStream: false,
    status: "registration_open",
    isPublic: true,
    isFeatured: false,
    loyaltyPointsAwarded: 200,
    prizeMoney: "10000",
    tags: ["provincial", "womens", "alberta"],
  },

  // Bonspiels (Club Level)
  {
    title: "Royal Vancouver Christmas Bonspiel",
    slug: "rv-christmas-2024",
    description: "Annual festive bonspiel featuring competitive and social divisions. Open to all skill levels with prizes and celebrations.",
    eventType: "competition",
    category: "bonspiel",
    level: "club",
    startDate: daysFromNow(15),
    endDate: daysFromNow(17),
    registrationOpenDate: daysAgo(60),
    registrationCloseDate: daysFromNow(7),
    city: "Vancouver",
    province: "BC",
    venueName: "Royal Vancouver Curling Club",
    venueAddress: "1630 West King Edward Avenue",
    maxParticipants: 32,
    currentParticipants: 29,
    registrationFee: "200",
    currency: "CAD",
    earlyBirdFee: "175",
    earlyBirdDeadline: daysFromNow(3),
    hasLiveScoring: false,
    hasLiveStream: false,
    status: "registration_open",
    isPublic: true,
    isFeatured: false,
    loyaltyPointsAwarded: 50,
    prizeMoney: "2000",
    tags: ["bonspiel", "social", "christmas", "club"],
  },
  {
    title: "Calgary Winter Club New Year's Bonspiel",
    slug: "cwc-newyears-2025",
    description: "Ring in the new year with competitive curling! Multiple divisions, prizes, and social events.",
    eventType: "competition",
    category: "bonspiel",
    level: "club",
    startDate: daysFromNow(40),
    endDate: daysFromNow(42),
    registrationOpenDate: daysAgo(30),
    registrationCloseDate: daysFromNow(30),
    city: "Calgary",
    province: "AB",
    venueName: "Calgary Winter Club",
    venueAddress: "615 10th Avenue SW",
    maxParticipants: 48,
    currentParticipants: 36,
    registrationFee: "225",
    currency: "CAD",
    earlyBirdFee: "200",
    earlyBirdDeadline: daysFromNow(20),
    hasLiveScoring: false,
    hasLiveStream: false,
    status: "registration_open",
    isPublic: true,
    isFeatured: false,
    loyaltyPointsAwarded: 50,
    prizeMoney: "3000",
    tags: ["bonspiel", "social", "new-year", "club"],
  },
  {
    title: "Granite Saskatoon Spring Bonspiel",
    slug: "granite-spring-2025",
    description: "Celebrate the end of the season with our traditional spring bonspiel. All levels welcome!",
    eventType: "competition",
    category: "bonspiel",
    level: "club",
    startDate: daysFromNow(90),
    endDate: daysFromNow(92),
    registrationOpenDate: daysFromNow(30),
    registrationCloseDate: daysFromNow(80),
    city: "Saskatoon",
    province: "SK",
    venueName: "Granite Curling Club",
    venueAddress: "420 Crescent Boulevard",
    maxParticipants: 40,
    currentParticipants: 12,
    registrationFee: "180",
    currency: "CAD",
    earlyBirdFee: "160",
    earlyBirdDeadline: daysFromNow(70),
    hasLiveScoring: false,
    hasLiveStream: false,
    status: "registration_open",
    isPublic: true,
    isFeatured: false,
    loyaltyPointsAwarded: 40,
    prizeMoney: "1500",
    tags: ["bonspiel", "spring", "club"],
  },

  // Clinics and Training
  {
    title: "Learn to Curl - Beginner Program",
    slug: "learn-to-curl-vancouver-jan",
    description: "Never curled before? Join our 6-week beginner program! Learn all the basics in a fun, supportive environment. Equipment provided.",
    eventType: "clinic",
    category: "training",
    level: "recreational",
    startDate: daysFromNow(10),
    endDate: daysFromNow(52),
    registrationOpenDate: daysAgo(45),
    registrationCloseDate: daysFromNow(5),
    city: "Vancouver",
    province: "BC",
    venueName: "Royal Vancouver Curling Club",
    venueAddress: "1630 West King Edward Avenue",
    maxParticipants: 24,
    currentParticipants: 18,
    registrationFee: "150",
    currency: "CAD",
    earlyBirdFee: "125",
    earlyBirdDeadline: daysAgo(5),
    hasLiveScoring: false,
    hasLiveStream: false,
    status: "registration_open",
    isPublic: true,
    isFeatured: true,
    loyaltyPointsAwarded: 25,
    tags: ["clinic", "beginner", "learn-to-curl", "training"],
  },
  {
    title: "High Performance Skills Camp",
    slug: "hp-skills-camp-calgary",
    description: "Advanced skills camp with national team coaches. Focus on delivery technique, reading ice, and strategy for competitive curlers.",
    eventType: "clinic",
    category: "skills",
    level: "national",
    startDate: daysFromNow(25),
    endDate: daysFromNow(27),
    registrationOpenDate: daysAgo(60),
    registrationCloseDate: daysFromNow(15),
    city: "Calgary",
    province: "AB",
    venueName: "Calgary Winter Club",
    venueAddress: "615 10th Avenue SW",
    maxParticipants: 32,
    currentParticipants: 30,
    registrationFee: "450",
    currency: "CAD",
    requiresApproval: true,
    hasLiveScoring: false,
    hasLiveStream: false,
    status: "registration_open",
    isPublic: true,
    isFeatured: true,
    loyaltyPointsAwarded: 100,
    tags: ["clinic", "high-performance", "skills", "training"],
  },
  {
    title: "Junior Development Camp",
    slug: "junior-dev-camp-toronto",
    description: "Week-long development camp for junior curlers aged 12-18. Work with experienced coaches on all aspects of the game.",
    eventType: "clinic",
    category: "training",
    level: "provincial",
    startDate: daysFromNow(60),
    endDate: daysFromNow(64),
    registrationOpenDate: daysFromNow(5),
    registrationCloseDate: daysFromNow(45),
    city: "Toronto",
    province: "ON",
    venueName: "High Park Club",
    venueAddress: "100 Indian Road",
    maxParticipants: 40,
    currentParticipants: 8,
    registrationFee: "350",
    currency: "CAD",
    earlyBirdFee: "300",
    earlyBirdDeadline: daysFromNow(35),
    hasLiveScoring: false,
    hasLiveStream: false,
    status: "draft",
    isPublic: false,
    isFeatured: false,
    loyaltyPointsAwarded: 75,
    tags: ["clinic", "juniors", "youth", "development"],
  },

  // League Nights (Recurring)
  {
    title: "Monday Night Mixed League - Winter 2025",
    slug: "monday-mixed-league-regina",
    description: "Weekly mixed doubles league for intermediate players. 12-week season with playoffs. New teams welcome!",
    eventType: "competition",
    category: "league",
    level: "club",
    startDate: daysFromNow(14),
    endDate: daysFromNow(98),
    registrationOpenDate: daysAgo(30),
    registrationCloseDate: daysFromNow(7),
    city: "Regina",
    province: "SK",
    venueName: "Regina Curling Centre",
    venueAddress: "2250 13th Avenue",
    maxParticipants: 32,
    currentParticipants: 28,
    registrationFee: "300",
    currency: "CAD",
    hasLiveScoring: false,
    hasLiveStream: false,
    status: "registration_open",
    isPublic: true,
    isFeatured: false,
    loyaltyPointsAwarded: 75,
    tags: ["league", "mixed", "winter", "recreational"],
  },
  {
    title: "Thursday Night Competitive League",
    slug: "thursday-comp-league-winnipeg",
    description: "Premier competitive league for experienced teams. Triple knockout format over 16 weeks.",
    eventType: "competition",
    category: "league",
    level: "club",
    startDate: daysFromNow(7),
    endDate: daysFromNow(119),
    registrationOpenDate: daysAgo(45),
    registrationCloseDate: daysFromNow(2),
    city: "Winnipeg",
    province: "MB",
    venueName: "Fort Rouge Curling Club",
    venueAddress: "625 Osborne Street",
    maxParticipants: 24,
    currentParticipants: 24,
    registrationFee: "400",
    currency: "CAD",
    hasLiveScoring: true,
    hasLiveStream: false,
    status: "registration_open",
    isPublic: true,
    isFeatured: false,
    loyaltyPointsAwarded: 100,
    tags: ["league", "competitive", "winter"],
  },

  // Social Events
  {
    title: "Annual Members Banquet",
    slug: "members-banquet-2025-montreal",
    description: "End of season celebration with dinner, awards, and entertainment. All members and guests welcome!",
    eventType: "social",
    category: null,
    level: "club",
    startDate: daysFromNow(100),
    endDate: daysFromNow(100),
    registrationOpenDate: daysFromNow(50),
    registrationCloseDate: daysFromNow(93),
    city: "Montreal",
    province: "QC",
    venueName: "Royal Montreal Curling Club",
    venueAddress: "1850 De Maisonneuve Boulevard West",
    maxParticipants: 200,
    currentParticipants: 0,
    registrationFee: "75",
    currency: "CAD",
    earlyBirdFee: "65",
    earlyBirdDeadline: daysFromNow(80),
    hasLiveScoring: false,
    hasLiveStream: false,
    status: "draft",
    isPublic: false,
    isFeatured: false,
    loyaltyPointsAwarded: 20,
    tags: ["social", "banquet", "celebration"],
  },
  {
    title: "Family Curling Day",
    slug: "family-day-2025-ottawa",
    description: "Bring the whole family for a day of curling fun! Activities for all ages, free hot chocolate, and prizes.",
    eventType: "social",
    category: null,
    level: "recreational",
    startDate: daysFromNow(55),
    endDate: daysFromNow(55),
    registrationOpenDate: daysFromNow(15),
    registrationCloseDate: daysFromNow(48),
    city: "Ottawa",
    province: "ON",
    venueName: "Ottawa Curling Club",
    venueAddress: "1148 Wellington Street West",
    maxParticipants: 100,
    currentParticipants: 0,
    registrationFee: "20",
    currency: "CAD",
    hasLiveScoring: false,
    hasLiveStream: false,
    status: "draft",
    isPublic: false,
    isFeatured: false,
    loyaltyPointsAwarded: 10,
    tags: ["social", "family", "youth", "recreational"],
  },

  // Fundraisers
  {
    title: "Curl for a Cause - Cancer Research Bonspiel",
    slug: "curl-for-cause-2025",
    description: "Annual charity bonspiel supporting cancer research. All proceeds go to the Canadian Cancer Society. Fun divisions, silent auction, and dinner included.",
    eventType: "fundraiser",
    category: "bonspiel",
    level: "club",
    startDate: daysFromNow(70),
    endDate: daysFromNow(71),
    registrationOpenDate: daysFromNow(20),
    registrationCloseDate: daysFromNow(63),
    city: "Toronto",
    province: "ON",
    venueName: "Tam Heather Curling Club",
    venueAddress: "481 Dunedin Avenue",
    maxParticipants: 32,
    currentParticipants: 0,
    registrationFee: "250",
    currency: "CAD",
    earlyBirdFee: "225",
    earlyBirdDeadline: daysFromNow(50),
    hasLiveScoring: false,
    hasLiveStream: false,
    status: "draft",
    isPublic: false,
    isFeatured: false,
    loyaltyPointsAwarded: 100,
    tags: ["fundraiser", "charity", "bonspiel", "social"],
  },

  // Broadcast Events
  {
    title: "Grand Slam of Curling - Masters",
    slug: "grand-slam-masters-2025",
    description: "Elite professional curling event featuring the world's top teams competing for a major purse and Grand Slam points.",
    eventType: "broadcast",
    category: "championship",
    level: "international",
    startDate: daysFromNow(80),
    endDate: daysFromNow(84),
    registrationOpenDate: null,
    registrationCloseDate: null,
    city: "Toronto",
    province: "ON",
    venueName: "Mattamy Athletic Centre",
    venueAddress: "50 Carlton Street",
    maxParticipants: 16,
    currentParticipants: 16,
    registrationFee: "0",
    currency: "CAD",
    requiresApproval: true,
    hasLiveScoring: true,
    hasLiveStream: true,
    streamUrl: "https://www.sportsnet.ca/curling",
    status: "published",
    isPublic: true,
    isFeatured: true,
    loyaltyPointsAwarded: 0,
    prizeMoney: "300000",
    tags: ["grand-slam", "professional", "broadcast", "international"],
  },

  // Virtual Events
  {
    title: "Rules and Strategy Webinar",
    slug: "rules-strategy-webinar-jan",
    description: "Online workshop covering advanced curling rules and strategic concepts. Perfect for competitive curlers looking to improve their game IQ.",
    eventType: "meeting",
    category: "training",
    level: "recreational",
    startDate: daysFromNow(18),
    endDate: daysFromNow(18),
    registrationOpenDate: daysAgo(20),
    registrationCloseDate: daysFromNow(17),
    city: null,
    province: null,
    isVirtual: true,
    virtualLink: "https://zoom.us/j/example",
    maxParticipants: 100,
    currentParticipants: 45,
    registrationFee: "25",
    currency: "CAD",
    hasLiveScoring: false,
    hasLiveStream: true,
    status: "registration_open",
    isPublic: true,
    isFeatured: false,
    loyaltyPointsAwarded: 15,
    tags: ["virtual", "webinar", "education", "strategy"],
  },
  {
    title: "Mental Performance for Curlers",
    slug: "mental-performance-webinar",
    description: "Learn mental training techniques from a sport psychologist specializing in curling. Manage pressure, build confidence, and improve focus.",
    eventType: "meeting",
    category: "training",
    level: "recreational",
    startDate: daysFromNow(32),
    endDate: daysFromNow(32),
    registrationOpenDate: daysFromNow(5),
    registrationCloseDate: daysFromNow(31),
    city: null,
    province: null,
    isVirtual: true,
    virtualLink: "https://zoom.us/j/example2",
    maxParticipants: 75,
    currentParticipants: 0,
    registrationFee: "35",
    currency: "CAD",
    hasLiveScoring: false,
    hasLiveStream: true,
    status: "draft",
    isPublic: false,
    isFeatured: false,
    loyaltyPointsAwarded: 20,
    tags: ["virtual", "webinar", "mental-training", "education"],
  },
];

export async function seedEvents() {
  console.log("📅 Seeding events...");
  
  try {
    const result = await db.insert(events).values(eventsData).returning();
    console.log(`✅ Seeded ${result.length} events`);
    return result;
  } catch (error) {
    console.error("❌ Error seeding events:", error);
    throw error;
  }
}
