// Seed data for loyalty tiers and rewards
import { db } from "./db-connection";
import { loyaltyTiers, rewards } from "../schema/loyalty";

export const loyaltyTiersData = [
  {
    name: "Stone",
    slug: "stone",
    minPoints: 0,
    maxPoints: 499,
    pointsMultiplier: "1.00",
    discountPercentage: "0.00",
    perks: [
      "Earn 1 point per dollar spent",
      "Birthday bonus: 50 points",
      "Access to member-only events",
      "Monthly newsletter",
    ],
    color: "#808080",
    badgeUrl: "/badges/stone.svg",
    description: "Entry level tier for all new members. Start earning points with every purchase!",
    orderIndex: 1,
    isActive: true,
  },
  {
    name: "Bronze",
    slug: "bronze",
    minPoints: 500,
    maxPoints: 1499,
    pointsMultiplier: "1.25",
    discountPercentage: "5.00",
    perks: [
      "Earn 1.25 points per dollar spent",
      "Birthday bonus: 100 points",
      "5% discount on merchandise",
      "Priority event registration",
      "Exclusive Bronze member events",
    ],
    color: "#CD7F32",
    badgeUrl: "/badges/bronze.svg",
    description: "Reach 500 points to unlock Bronze benefits and enhanced earning power.",
    orderIndex: 2,
    isActive: true,
  },
  {
    name: "Silver",
    slug: "silver",
    minPoints: 1500,
    maxPoints: 2999,
    pointsMultiplier: "1.50",
    discountPercentage: "10.00",
    perks: [
      "Earn 1.5 points per dollar spent",
      "Birthday bonus: 200 points",
      "10% discount on merchandise",
      "Free shipping on online orders",
      "VIP event access",
      "Complimentary coaching session annually",
    ],
    color: "#C0C0C0",
    badgeUrl: "/badges/silver.svg",
    description: "Silver tier members enjoy premium benefits and VIP access to exclusive events.",
    orderIndex: 3,
    isActive: true,
  },
  {
    name: "Gold",
    slug: "gold",
    minPoints: 3000,
    maxPoints: null,
    pointsMultiplier: "2.00",
    discountPercentage: "15.00",
    perks: [
      "Earn 2 points per dollar spent",
      "Birthday bonus: 500 points",
      "15% discount on merchandise",
      "Free shipping + express option",
      "VIP event access + guest passes",
      "Quarterly complimentary coaching",
      "Meet & greet with Team Canada curlers",
      "Gold member appreciation events",
    ],
    color: "#FFD700",
    badgeUrl: "/badges/gold.svg",
    description: "Our highest tier - enjoy maximum benefits and exclusive experiences with Team Canada.",
    orderIndex: 4,
    isActive: true,
  },
];

export const rewardsData = [
  // Low-tier rewards (100-500 points)
  {
    name: "Curling Canada T-Shirt",
    slug: "cc-tshirt",
    description: "Official Curling Canada t-shirt in your choice of size. High-quality cotton blend with official logo.",
    category: "merchandise",
    pointsCost: 250,
    redemptionType: "physical",
    isActive: true,
    stock: 500,
    maxRedemptionsPerUser: 5,
    imageUrl: "/rewards/tshirt.jpg",
    features: ["Available in S-XXL", "Red, Navy, or White", "60% cotton, 40% polyester"],
    redemptionInstructions: "Select size and color during checkout. Ships within 5-7 business days.",
    tags: ["apparel", "tshirt", "merchandise"],
  },
  {
    name: "Curling Canada Baseball Cap",
    slug: "cc-cap",
    description: "Adjustable baseball cap with embroidered Curling Canada logo. One size fits most.",
    category: "merchandise",
    pointsCost: 200,
    redemptionType: "physical",
    isActive: true,
    stock: 300,
    maxRedemptionsPerUser: 3,
    imageUrl: "/rewards/cap.jpg",
    features: ["Adjustable strap", "Embroidered logo", "Breathable mesh", "Red, Navy, or Black"],
    redemptionInstructions: "Select color during checkout. Ships within 5-7 business days.",
    tags: ["apparel", "cap", "merchandise"],
  },
  {
    name: "Free Event Entry - Club Level",
    slug: "free-entry-club",
    description: "Complimentary entry to any club-level bonspiel or social event. Valid for one year.",
    category: "event_perks",
    pointsCost: 300,
    redemptionType: "code",
    isActive: true,
    stock: null,
    maxRedemptionsPerUser: 10,
    imageUrl: "/rewards/event-ticket.jpg",
    features: ["Valid for 1 year", "Club-level events only", "Subject to availability"],
    redemptionInstructions: "Use the provided code when registering for qualifying events.",
    termsAndConditions: "Valid for club-level bonspiels and social events only. Not valid for championships. Subject to event availability.",
    tags: ["event", "bonspiel", "club"],
  },
  {
    name: "Curling Canada Water Bottle",
    slug: "cc-water-bottle",
    description: "Insulated stainless steel water bottle with Curling Canada branding. Keeps drinks cold for 24 hours.",
    category: "merchandise",
    pointsCost: 350,
    redemptionType: "physical",
    isActive: true,
    stock: 250,
    maxRedemptionsPerUser: 3,
    imageUrl: "/rewards/water-bottle.jpg",
    features: ["750ml capacity", "Stainless steel", "Double-wall insulated", "Leak-proof lid"],
    redemptionInstructions: "Ships within 5-7 business days.",
    tags: ["merchandise", "water-bottle", "gear"],
  },
  {
    name: "$10 Merchandise Credit",
    slug: "10-dollar-credit",
    description: "Apply a $10 credit toward any merchandise purchase in our online store.",
    category: "discounts",
    pointsCost: 100,
    redemptionType: "code",
    isActive: true,
    stock: null,
    maxRedemptionsPerUser: 20,
    imageUrl: "/rewards/gift-card.jpg",
    features: ["Use online or in-store", "Valid for 6 months", "Cannot be combined with other discounts"],
    redemptionInstructions: "Apply the provided code at checkout.",
    termsAndConditions: "Valid for 180 days from redemption date. Cannot be combined with other promotional discounts. Non-transferable.",
    tags: ["discount", "credit", "voucher"],
  },

  // Mid-tier rewards (500-1500 points)
  {
    name: "Curling Canada Hoodie",
    slug: "cc-hoodie",
    description: "Premium zip-up hoodie with Curling Canada logo. Soft fleece interior, perfect for rink or casual wear.",
    category: "merchandise",
    pointsCost: 750,
    redemptionType: "physical",
    isActive: true,
    stock: 200,
    maxRedemptionsPerUser: 3,
    imageUrl: "/rewards/hoodie.jpg",
    features: ["S-XXL sizes", "Red, Navy, or Charcoal", "80% cotton, 20% polyester fleece", "Full zipper", "Kangaroo pocket"],
    redemptionInstructions: "Select size and color during checkout. Ships within 7-10 business days.",
    tags: ["apparel", "hoodie", "merchandise"],
  },
  {
    name: "Performance Curling Gloves",
    slug: "performance-gloves",
    description: "Professional-grade curling gloves with enhanced grip and flexibility. Used by Team Canada athletes.",
    category: "merchandise",
    pointsCost: 600,
    redemptionType: "physical",
    isActive: true,
    stock: 150,
    maxRedemptionsPerUser: 2,
    imageUrl: "/rewards/gloves.jpg",
    features: ["S-XL sizes", "Leather palm", "Reinforced fingertips", "Breathable mesh", "Touch-screen compatible"],
    redemptionInstructions: "Select size during checkout. Ships within 5-7 business days.",
    tags: ["equipment", "gloves", "performance"],
  },
  {
    name: "Free Event Entry - Provincial",
    slug: "free-entry-provincial",
    description: "Complimentary entry to any provincial-level bonspiel. Valid for one year.",
    category: "event_perks",
    pointsCost: 800,
    redemptionType: "code",
    isActive: true,
    stock: null,
    maxRedemptionsPerUser: 5,
    imageUrl: "/rewards/provincial-ticket.jpg",
    features: ["Valid for 1 year", "Provincial events", "Subject to availability"],
    redemptionInstructions: "Use the provided code when registering for qualifying provincial events.",
    termsAndConditions: "Valid for provincial bonspiels only. Not valid for provincial championships. Subject to event availability.",
    tags: ["event", "bonspiel", "provincial"],
  },
  {
    name: "Private Coaching Session",
    slug: "private-coaching",
    description: "One-hour private coaching session with a certified Level 3 coach. Focus on delivery, strategy, or game management.",
    category: "experiences",
    pointsCost: 1200,
    redemptionType: "code",
    isActive: true,
    stock: null,
    maxRedemptionsPerUser: 10,
    imageUrl: "/rewards/coaching.jpg",
    features: ["60 minutes", "Level 3 certified coach", "Video analysis", "Personalized drills", "Follow-up notes"],
    redemptionInstructions: "Contact the rewards team to schedule your session at a participating club.",
    termsAndConditions: "Valid for 180 days from redemption. Subject to coach and facility availability. Must be scheduled minimum 2 weeks in advance.",
    tags: ["coaching", "training", "experience"],
  },
  {
    name: "$50 Merchandise Credit",
    slug: "50-dollar-credit",
    description: "Apply a $50 credit toward any merchandise purchase in our online store.",
    category: "discounts",
    pointsCost: 500,
    redemptionType: "code",
    isActive: true,
    stock: null,
    maxRedemptionsPerUser: 10,
    imageUrl: "/rewards/gift-card.jpg",
    features: ["Use online or in-store", "Valid for 6 months", "Cannot be combined with other discounts"],
    redemptionInstructions: "Apply the provided code at checkout.",
    termsAndConditions: "Valid for 180 days from redemption date. Cannot be combined with other promotional discounts. Non-transferable.",
    tags: ["discount", "credit", "voucher"],
  },

  // High-tier rewards (1500+ points)
  {
    name: "Team Canada Replica Jersey",
    slug: "team-canada-jersey",
    description: "Official Team Canada curling jersey - exact replica worn by our national teams. Premium quality with sublimated graphics.",
    category: "merchandise",
    pointsCost: 1500,
    redemptionType: "physical",
    isActive: true,
    stock: 100,
    maxRedemptionsPerUser: 2,
    imageUrl: "/rewards/jersey.jpg",
    features: ["S-XXL sizes", "Moisture-wicking fabric", "Sublimated graphics", "Official Team Canada crest"],
    redemptionInstructions: "Select size during checkout. Ships within 10-14 business days.",
    tags: ["apparel", "jersey", "team-canada", "premium"],
  },
  {
    name: "VIP Championship Experience",
    slug: "vip-championship",
    description: "VIP package for a major Curling Canada championship: premium seating, meet & greet, exclusive merchandise. Subject to availability.",
    category: "experiences",
    pointsCost: 3000,
    redemptionType: "code",
    isActive: true,
    stock: 50,
    maxRedemptionsPerUser: 2,
    minTierRequired: "silver",
    imageUrl: "/rewards/vip-experience.jpg",
    features: ["2 VIP seats", "Meet & greet with athletes", "VIP merchandise package", "VIP lounge access", "Commemorative photo"],
    redemptionInstructions: "Contact the rewards team to book your VIP experience. Minimum 60 days advance notice required.",
    termsAndConditions: "Valid for one year. Subject to championship availability. Minimum 60 days advance booking required. Package is for 2 people.",
    tags: ["experience", "vip", "championship", "premium"],
  },
  {
    name: "Equipment Package - Broom & Shoes",
    slug: "equipment-package",
    description: "Complete curling equipment package: premium broom (pad included) and professional curling shoes. Your choice of styles.",
    category: "merchandise",
    pointsCost: 2500,
    redemptionType: "physical",
    isActive: true,
    stock: 75,
    maxRedemptionsPerUser: 1,
    minTierRequired: "bronze",
    imageUrl: "/rewards/equipment-package.jpg",
    features: ["Premium carbon fiber broom", "Professional curling shoes", "Men's 6-14, Women's 5-12", "Choice of brands"],
    redemptionInstructions: "Complete the equipment selection form after redemption. Allow 3-4 weeks for delivery.",
    termsAndConditions: "One package per member. Sizing and brand selection required within 30 days of redemption.",
    tags: ["equipment", "broom", "shoes", "package", "premium"],
  },
  {
    name: "Championship Weekend Package",
    slug: "championship-weekend",
    description: "All-inclusive weekend at a major championship: hotel, meals, VIP seating, behind-the-scenes access. Once-in-a-lifetime experience!",
    category: "experiences",
    pointsCost: 5000,
    redemptionType: "code",
    isActive: true,
    stock: 25,
    maxRedemptionsPerUser: 1,
    minTierRequired: "gold",
    imageUrl: "/rewards/weekend-package.jpg",
    features: ["2 nights hotel", "All meals", "VIP seating", "Behind-the-scenes tour", "Meet & greet", "Official merchandise", "On-ice photo op"],
    redemptionInstructions: "Contact the rewards team to book. Minimum 90 days advance notice required. Travel to/from venue not included.",
    termsAndConditions: "Valid for one year. Subject to championship availability and hotel room availability. Minimum 90 days advance booking. Package for 2 people (double occupancy). Travel to/from venue not included.",
    tags: ["experience", "vip", "championship", "weekend", "premium", "exclusive"],
  },
  {
    name: "$250 Merchandise Credit",
    slug: "250-dollar-credit",
    description: "Apply a $250 credit toward any merchandise or equipment purchase. Build your dream curling setup!",
    category: "discounts",
    pointsCost: 2500,
    redemptionType: "code",
    isActive: true,
    stock: null,
    maxRedemptionsPerUser: 3,
    minTierRequired: "bronze",
    imageUrl: "/rewards/gift-card.jpg",
    features: ["Use online or in-store", "Valid for 1 year", "Can be used on equipment"],
    redemptionInstructions: "Apply the provided code at checkout.",
    termsAndConditions: "Valid for 365 days from redemption date. Cannot be combined with major promotional discounts. Non-transferable.",
    tags: ["discount", "credit", "voucher", "premium"],
  },
];

export async function seedLoyalty() {
  console.log("⭐ Seeding loyalty tiers and rewards...");
  
  try {
    // Seed tiers
    const tiersResult = await db.insert(loyaltyTiers).values(loyaltyTiersData).returning();
    console.log(`✅ Seeded ${tiersResult.length} loyalty tiers`);
    
    // Seed rewards
    const rewardsResult = await db.insert(rewards).values(rewardsData).returning();
    console.log(`✅ Seeded ${rewardsResult.length} rewards`);
    
    return { tiers: tiersResult, rewards: rewardsResult };
  } catch (error) {
    console.error("❌ Error seeding loyalty data:", error);
    throw error;
  }
}
