
import React, { useState } from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { X, Plus, Loader2 } from 'lucide-react';

import { useSecureForm } from '../hooks/useSecureForm';
import { SecureInput } from '../ui/SecureInput';
import { SecureTextarea } from '../ui/SecureTextarea';
import { inputValidationService } from '../services/InputValidationService';

const CreateEventModal = ({ isOpen, onClose, onEventCreated }) => {
  const formSchema = {
    name: { type: 'text', minLength: 3, maxLength: 200, fieldName: 'Event Name', required: true },
    description: { type: 'text', maxLength: 2000, fieldName: 'Description', required: false },
    start_date: { type: 'date', fieldName: 'Start Date', required: true },
    end_date: { type: 'date', fieldName: 'End Date', required: true },
    'venue.name': { type: 'text', minLength: 2, maxLength: 200, fieldName: 'Venue Name', required: true },
    'venue.city': { type: 'text', minLength: 2, maxLength: 100, fieldName: 'City', required: true },
    'venue.province': { type: 'text', fieldName: 'Province', required: true }, // This will be validated as text, select ensures a value
    event_type: { type: 'text', fieldName: 'Event Type', required: true }, // Select ensures a value
    livestream_url: { type: 'url', required: false },
    ticket_url: { type: 'url', required: false },
    registration_url: { type: 'url', required: false },
    volunteer_url: { type: 'url', required: false },
    is_featured: { type: 'boolean', required: false }
  };

  const initialFormData = {
    name: '',
    description: '',
    start_date: '',
    end_date: '',
    'venue.name': '',
    'venue.city': '',
    'venue.province': '',
    event_type: 'club',
    livestream_url: '',
    ticket_url: '',
    registration_url: '',
    volunteer_url: '',
    is_featured: false
  };

  const [tags, setTags] = useState([]);
  const [sponsors, setSponsors] = useState([]);
  const [audience, setAudience] = useState([]); // Assuming audience is also an array state

  const [newTag, setNewTag] = useState('');
  const [newSponsor, setNewSponsor] = useState('');

  const { formData, errors, isSubmitting, handleChange, handleSubmit } = useSecureForm(
    formSchema,
    initialFormData,
    async (sanitizedData, csrfToken) => { // csrfToken would be used for actual API call
      // Reconstruct nested venue object
      const eventData = {
        ...sanitizedData,
        venue: {
          name: sanitizedData['venue.name'],
          city: sanitizedData['venue.city'],
          province: sanitizedData['venue.province']
        },
        id: Date.now(), // In real app, this would be generated by the backend
        status: new Date(sanitizedData.start_date) > new Date() ? 'upcoming' : 'live',
        created_date: new Date().toISOString(),
        tags: tags,
        sponsors: sponsors,
        audience: audience // Include the audience state
      };

      // Remove flattened venue fields from the main object
      delete eventData['venue.name'];
      delete eventData['venue.city'];
      delete eventData['venue.province'];

      onEventCreated(eventData);
      onClose();
    }
  );

  const handleArrayAdd = (value, setter) => {
    if (!value) return;
    
    // ✅ VALIDATE INPUT for tags/sponsors
    const validation = inputValidationService.validateText(value, {
      maxLength: 100, // Max length for tags/sponsors
      allowSpecialChars: true // Tags/sponsors might have some special chars, adjust as needed
    });

    if (!validation.valid) {
      // Potentially display a temporary error message for the tag/sponsor input
      console.error(`Validation error for tag/sponsor: ${validation.message}`);
      return;
    }

    setter(prev => {
      // Ensure sanitized value is added and no duplicates
      if (prev.includes(validation.sanitized)) return prev;
      return [...prev, validation.sanitized];
    });
  };

  const handleArrayRemove = (value, setter) => {
    setter(prev => prev.filter(item => item !== value));
  };

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="max-w-4xl max-h-[90vh] overflow-y-auto bg-brand-card-bg border-brand-border">
        <DialogHeader>
          <DialogTitle className="text-2xl text-brand-text-primary">Create New Event</DialogTitle>
        </DialogHeader>

        <form onSubmit={handleSubmit} className="space-y-6">
          {errors._form && (
            <div className="bg-red-500/10 border border-red-500 rounded-lg p-3 text-red-500 text-sm">
              {errors._form}
            </div>
          )}

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {/* Basic Information */}
            <Card className="bg-brand-charcoal border-brand-border">
              <CardHeader>
                <CardTitle className="text-lg">Basic Information</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div>
                  <label className="block text-sm font-medium text-brand-text-primary mb-2">
                    Event Name *
                  </label>
                  <SecureInput
                    value={formData.name || ''}
                    onChange={(e) => handleChange('name', e.target.value)}
                    className="bg-brand-card-bg border-brand-border text-brand-text-primary"
                    maxLength={200}
                    required // Visual indicator, validation is handled by useSecureForm
                  />
                  {errors.name && <p className="text-red-500 text-xs mt-1">{errors.name}</p>}
                </div>

                <div>
                  <label className="block text-sm font-medium text-brand-text-primary mb-2">
                    Description
                  </label>
                  <SecureTextarea
                    value={formData.description || ''}
                    onChange={(e) => handleChange('description', e.target.value)}
                    className="bg-brand-card-bg border-brand-border text-brand-text-primary h-24"
                    maxLength={2000}
                  />
                  {errors.description && <p className="text-red-500 text-xs mt-1">{errors.description}</p>}
                </div>

                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <label className="block text-sm font-medium text-brand-text-primary mb-2">
                      Start Date *
                    </label>
                    <Input
                      type="date"
                      value={formData.start_date || ''}
                      onChange={(e) => handleChange('start_date', e.target.value)}
                      className="bg-brand-card-bg border-brand-border text-brand-text-primary"
                      required
                    />
                    {errors.start_date && <p className="text-red-500 text-xs mt-1">{errors.start_date}</p>}
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-brand-text-primary mb-2">
                      End Date *
                    </label>
                    <Input
                      type="date"
                      value={formData.end_date || ''}
                      onChange={(e) => handleChange('end_date', e.target.value)}
                      className="bg-brand-card-bg border-brand-border text-brand-text-primary"
                      required
                    />
                    {errors.end_date && <p className="text-red-500 text-xs mt-1">{errors.end_date}</p>}
                  </div>
                </div>

                <div>
                  <label className="block text-sm font-medium text-brand-text-primary mb-2">
                    Event Type
                  </label>
                  <Select 
                    value={formData.event_type || 'club'} 
                    onValueChange={(value) => handleChange('event_type', value)}
                  >
                    <SelectTrigger className="bg-brand-card-bg border-brand-border">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="championship">Championship</SelectItem>
                      <SelectItem value="provincial">Provincial</SelectItem>
                      <SelectItem value="club">Club Event</SelectItem>
                      <SelectItem value="learn_to_curl">Learn to Curl</SelectItem>
                      <SelectItem value="tournament">Tournament</SelectItem>
                    </SelectContent>
                  </Select>
                  {errors.event_type && <p className="text-red-500 text-xs mt-1">{errors.event_type}</p>}
                </div>
              </CardContent>
            </Card>

            {/* Venue Information */}
            <Card className="bg-brand-charcoal border-brand-border">
              <CardHeader>
                <CardTitle className="text-lg">Venue Information</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div>
                  <label className="block text-sm font-medium text-brand-text-primary mb-2">
                    Venue Name *
                  </label>
                  <SecureInput
                    value={formData['venue.name'] || ''}
                    onChange={(e) => handleChange('venue.name', e.target.value)}
                    className="bg-brand-card-bg border-brand-border text-brand-text-primary"
                    maxLength={200}
                    required
                  />
                  {errors['venue.name'] && <p className="text-red-500 text-xs mt-1">{errors['venue.name']}</p>}
                </div>

                <div>
                  <label className="block text-sm font-medium text-brand-text-primary mb-2">
                    City *
                  </label>
                  <SecureInput
                    value={formData['venue.city'] || ''}
                    onChange={(e) => handleChange('venue.city', e.target.value)}
                    className="bg-brand-card-bg border-brand-border text-brand-text-primary"
                    maxLength={100}
                    required
                  />
                  {errors['venue.city'] && <p className="text-red-500 text-xs mt-1">{errors['venue.city']}</p>}
                </div>

                <div>
                  <label className="block text-sm font-medium text-brand-text-primary mb-2">
                    Province *
                  </label>
                  <Select 
                    value={formData['venue.province'] || ''} 
                    onValueChange={(value) => handleChange('venue.province', value)}
                  >
                    <SelectTrigger className="bg-brand-card-bg border-brand-border">
                      <SelectValue placeholder="Select Province" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="BC">British Columbia</SelectItem>
                      <SelectItem value="AB">Alberta</SelectItem>
                      <SelectItem value="SK">Saskatchewan</SelectItem>
                      <SelectItem value="MB">Manitoba</SelectItem>
                      <SelectItem value="ON">Ontario</SelectItem>
                      <SelectItem value="QC">Quebec</SelectItem>
                      <SelectItem value="NB">New Brunswick</SelectItem>
                      <SelectItem value="NS">Nova Scotia</SelectItem>
                      <SelectItem value="PE">Prince Edward Island</SelectItem>
                      <SelectItem value="NL">Newfoundland</SelectItem>
                      <SelectItem value="NT">Northwest Territories</SelectItem>
                      <SelectItem value="NU">Nunavut</SelectItem>
                      <SelectItem value="YT">Yukon</SelectItem>
                    </SelectContent>
                  </Select>
                  {errors['venue.province'] && <p className="text-red-500 text-xs mt-1">{errors['venue.province']}</p>}
                </div>
              </CardContent>
            </Card>
          </div>

          {/* URLs and Links */}
          <Card className="bg-brand-charcoal border-brand-border">
            <CardHeader>
              <CardTitle className="text-lg">Links & URLs</CardTitle>
            </CardHeader>
            <CardContent className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium text-brand-text-primary mb-2">
                  Live Stream URL
                </label>
                <SecureInput
                  value={formData.livestream_url || ''}
                  onChange={(e) => handleChange('livestream_url', e.target.value)}
                  className="bg-brand-card-bg border-brand-border text-brand-text-primary"
                  placeholder="https://..."
                />
                {errors.livestream_url && <p className="text-red-500 text-xs mt-1">{errors.livestream_url}</p>}
              </div>

              <div>
                <label className="block text-sm font-medium text-brand-text-primary mb-2">
                  Ticket URL
                </label>
                <SecureInput
                  value={formData.ticket_url || ''}
                  onChange={(e) => handleChange('ticket_url', e.target.value)}
                  className="bg-brand-card-bg border-brand-border text-brand-text-primary"
                  placeholder="https://..."
                />
                {errors.ticket_url && <p className="text-red-500 text-xs mt-1">{errors.ticket_url}</p>}
              </div>

              <div>
                <label className="block text-sm font-medium text-brand-text-primary mb-2">
                  Registration URL
                </label>
                <SecureInput
                  value={formData.registration_url || ''}
                  onChange={(e) => handleChange('registration_url', e.target.value)}
                  className="bg-brand-card-bg border-brand-border text-brand-text-primary"
                  placeholder="https://..."
                />
                {errors.registration_url && <p className="text-red-500 text-xs mt-1">{errors.registration_url}</p>}
              </div>

              <div>
                <label className="block text-sm font-medium text-brand-text-primary mb-2">
                  Volunteer URL
                </label>
                <SecureInput
                  value={formData.volunteer_url || ''}
                  onChange={(e) => handleChange('volunteer_url', e.target.value)}
                  className="bg-brand-card-bg border-brand-border text-brand-text-primary"
                  placeholder="https://..."
                />
                {errors.volunteer_url && <p className="text-red-500 text-xs mt-1">{errors.volunteer_url}</p>}
              </div>
            </CardContent>
          </Card>

          {/* Tags and Sponsors */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <Card className="bg-brand-charcoal border-brand-border">
              <CardHeader>
                <CardTitle className="text-lg">Tags</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="flex gap-2">
                  <SecureInput
                    value={newTag}
                    onChange={(e) => setNewTag(e.target.value)}
                    placeholder="Add tag..."
                    className="bg-brand-card-bg border-brand-border text-brand-text-primary"
                    maxLength={50}
                    onKeyPress={(e) => {
                      if (e.key === 'Enter') {
                        e.preventDefault();
                        handleArrayAdd(newTag, setTags);
                        setNewTag('');
                      }
                    }}
                  />
                  <Button 
                    type="button" 
                    onClick={() => {
                      handleArrayAdd(newTag, setTags);
                      setNewTag('');
                    }}
                  >
                    <Plus className="w-4 h-4" />
                  </Button>
                </div>
                <div className="flex flex-wrap gap-2">
                  {tags.map(tag => (
                    <Badge key={tag} variant="outline" className="border-brand-border text-brand-text-secondary">
                      {tag}
                      <button
                        type="button"
                        onClick={() => handleArrayRemove(tag, setTags)}
                        className="ml-2 text-red-400 hover:text-red-300"
                      >
                        <X className="w-3 h-3" />
                      </button>
                    </Badge>
                  ))}
                </div>
              </CardContent>
            </Card>

            <Card className="bg-brand-charcoal border-brand-border">
              <CardHeader>
                <CardTitle className="text-lg">Sponsors</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="flex gap-2">
                  <SecureInput
                    value={newSponsor}
                    onChange={(e) => setNewSponsor(e.target.value)}
                    placeholder="Add sponsor..."
                    className="bg-brand-card-bg border-brand-border text-brand-text-primary"
                    maxLength={100}
                    onKeyPress={(e) => {
                      if (e.key === 'Enter') {
                        e.preventDefault();
                        handleArrayAdd(newSponsor, setSponsors);
                        setNewSponsor('');
                      }
                    }}
                  />
                  <Button 
                    type="button" 
                    onClick={() => {
                      handleArrayAdd(newSponsor, setSponsors);
                      setNewSponsor('');
                    }}
                  >
                    <Plus className="w-4 h-4" />
                  </Button>
                </div>
                <div className="flex flex-wrap gap-2">
                  {sponsors.map(sponsor => (
                    <Badge key={sponsor} variant="outline" className="border-brand-border text-brand-text-secondary">
                      {sponsor}
                      <button
                        type="button"
                        onClick={() => handleArrayRemove(sponsor, setSponsors)}
                        className="ml-2 text-red-400 hover:text-red-300"
                      >
                        <X className="w-3 h-3" />
                      </button>
                    </Badge>
                  ))}
                </div>
              </CardContent>
            </Card>
          </div>

          {/* Submit Buttons */}
          <div className="flex justify-end gap-4 pt-4">
            <Button type="button" variant="outline" onClick={onClose} disabled={isSubmitting}>
              Cancel
            </Button>
            <Button 
              type="submit" 
              className="bg-brand-red hover:bg-red-700" 
              disabled={isSubmitting}
            >
              {isSubmitting ? (
                <>
                  <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                  Creating...
                </>
              ) : (
                'Create Event'
              )}
            </Button>
          </div>
        </form>
      </DialogContent>
    </Dialog>
  );
};

export default CreateEventModal;
