export const maDashboardData = {
  "All Regions": {
    metrics: {
      totalMembers: "85,670",
      memberGrowth: "+5.2%",
      totalClubs: 1012,
      totalDonations: "$1,250,840",
      complianceRate: "88%",
    },
    membershipTrend: [
      { month: 'Jan', members: 78200 },
      { month: 'Feb', members: 79100 },
      { month: 'Mar', members: 79500 },
      { month: 'Apr', members: 80300 },
      { month: 'May', members: 81500 },
      { month: 'Jun', members: 82100 },
      { month: 'Jul', members: 82900 },
      { month: 'Aug', members: 83500 },
      { month: 'Sep', members: 84200 },
      { month: 'Oct', members: 85100 },
      { month: 'Nov', members: 85500 },
      { month: 'Dec', members: 85670 },
    ],
    donationCategories: [
      { name: 'Youth Programs', value: 450300 },
      { name: 'Club Support', value: 310200 },
      { name: 'Athlete Dev', value: 250140 },
      { name: 'General Fund', value: 240200 },
    ],
    leaderboard: [
        { rank: 1, clubName: "Toronto Granite Club", metric: "+150 members" },
        { rank: 2, clubName: "Saville Community Sports Centre", metric: "+125 members" },
        { rank: 3, clubName: "Calgary Curling Club", metric: "$50,000 raised" },
        { rank: 4, clubName: "St. Vital Curling Club", metric: "100% Compliance" },
        { rank: 5, clubName: "Vancouver Curling Club", metric: "+98 members" },
    ],
  },
  "Ontario": {
    metrics: {
      totalMembers: "32,150",
      memberGrowth: "+4.8%",
      totalClubs: 350,
      totalDonations: "$480,500",
      complianceRate: "92%",
    },
    membershipTrend: [
      { month: 'Jan', members: 30100 },
      { month: 'Feb', members: 30500 },
      { month: 'Mar', members: 30700 },
      { month: 'Apr', members: 30900 },
      { month: 'May', members: 31200 },
      { month: 'Jun', members: 31400 },
      { month: 'Jul', members: 31600 },
      { month: 'Aug', members: 31800 },
      { month: 'Sep', members: 32000 },
      { month: 'Oct', members: 32100 },
      { month: 'Nov', members: 32120 },
      { month: 'Dec', members: 32150 },
    ],
    donationCategories: [
      { name: 'Youth Programs', value: 200000 },
      { name: 'Club Support', value: 120000 },
      { name: 'Athlete Dev', value: 90500 },
      { name: 'General Fund', value: 70000 },
    ],
    leaderboard: [
        { rank: 1, clubName: "Toronto Granite Club", metric: "+150 members" },
        { rank: 2, clubName: "Ottawa Curling Club", metric: "$25,000 raised" },
        { rank: 3, clubName: "Listowel Curling Club", metric: "100% Compliance" },
        { rank: 4, clubName: "Royal Canadian Curling Club", metric: "+80 members" },
        { rank: 5, clubName: "Guelph Curling Club", metric: "$15,000 raised" },
    ],
  },
  "Alberta": {
    metrics: {
      totalMembers: "15,800",
      memberGrowth: "+6.1%",
      totalClubs: 180,
      totalDonations: "$210,000",
      complianceRate: "85%",
    },
     membershipTrend: [
      { month: 'Jan', members: 14500 },
      { month: 'Feb', members: 14700 },
      { month: 'Mar', members: 14800 },
      { month: 'Apr', members: 15000 },
      { month: 'May', members: 15100 },
      { month: 'Jun', members: 15200 },
      { month: 'Jul', members: 15300 },
      { month: 'Aug', members: 15400 },
      { month: 'Sep', members: 15500 },
      { month: 'Oct', members: 15600 },
      { month: 'Nov', members: 15750 },
      { month: 'Dec', members: 15800 },
    ],
    donationCategories: [
      { name: 'Youth Programs', value: 90000 },
      { name: 'Club Support', value: 55000 },
      { name: 'Athlete Dev', value: 40000 },
      { name: 'General Fund', value: 25000 },
    ],
    leaderboard: [
        { rank: 1, clubName: "Saville Community Sports Centre", metric: "+125 members" },
        { rank: 2, clubName: "Calgary Curling Club", metric: "$50,000 raised" },
        { rank: 3, clubName: "The Glencoe Club", metric: "+90 members" },
        { rank: 4, clubName: "Red Deer Curling Centre", metric: "98% Compliance" },
        { rank: 5, clubName: "Lethbridge Curling Club", metric: "$12,000 raised" },
    ],
  }
};

export const maRegions = ["All Regions", "Ontario", "Alberta", "British Columbia", "Manitoba", "Saskatchewan", "Quebec", "Nova Scotia", "New Brunswick", "Newfoundland and Labrador", "Prince Edward Island", "Northern Ontario", "Yukon", "Northwest Territories", "Nunavut"];